name: Build and deploy a container image to Azure Web Apps

on:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: fry-bot
  CONTAINER_REGISTRY: ghcr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

    - name: 'Login via Azure CLI'
      uses: azure/login@1f63701bf3e6892515f1b7ce2d2bf1708b46beaf
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      
    - name: Login to Docker Hub
      uses: docker/login-action@6af3c118c8376c675363897acf1757f7a9be6583
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker Build & Push to ${{ env.CONTAINER_REGISTRY }}
      run: |
          docker build . -t ${{ env.CONTAINER_REGISTRY }}/tebriel/fry-bot:${{ github.sha }} -t ${{ env.CONTAINER_REGISTRY }}/tebriel/fry-bot:latest
          docker push ${{ env.CONTAINER_REGISTRY }}/tebriel/fry-bot:${{ github.sha }}
          docker push ${{ env.CONTAINER_REGISTRY }}/tebriel/fry-bot:latest

    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@28cafb864979bc5b44cd1f3fd45522727eb5a3db'
      with:
        resource-group: fry-bot
        image: ${{ env.CONTAINER_REGISTRY }}/tebriel/fry-bot:${{ github.sha }}
        name: fry-bot
        location: 'east us 2'
        cpu: '1'
        memory: '1.5'
        environment-variables: GITHUB_SHA=${{ github.sha }} ENVIRONMENT=production
        secure-environment-variables: ''
        ip-address: 'Public'
        dns-name-label: 'fry-bot'
        log-analytics-workspace: 'd840f85d-a50e-4e6c-b31c-61c29b88f374'
        log-type: 'ContainerInstanceLogs'
        log-analytics-workspace-key: '$${ secrets.WORKSPACE_KEY }}'
