name: Build and deploy a container image to Azure Web Apps

on:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: fry-bot
  CONTAINER_REGISTRY: ghcr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@main

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker Build & Push to ACR
      run: |
          docker build . -t ${{ env.CONTAINER_REGISTRY }}/tebriel/fry-bot:${{ github.sha }} -t ${{ env.CONTAINER_REGISTRY }}/tebriel/fry-bot:latest
          docker push ${{ env.CONTAINER_REGISTRY }}/tebriel/fry-bot:${{ github.sha }}
          docker push ${{ env.CONTAINER_REGISTRY }}/tebriel/fry-bot:latest

    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1.1.3'
      with:
        resource-group: fry-bot
        image: ${{ env.CONTAINER_REGISTRY }}/tebriel/fry-bot:${{ github.sha }}
        name: fry-bot
        location: 'east us 2'
        cpu: '1'
        memory: '1.5'
        environment-variables: GITHUB_SHA=${{ github.sha }}
        secure-environment-variables: BOT_GATEWAY_TOKEN=${{ secrets.BOT_GATEWAY_TOKEN }}
        ip-address: 'Public'
        dns-name-label: 'fry-bot'
